Fix samples, add require_script_file

diff --git a/samples/colors b/samples/colors
--- a/samples/colors
+++ b/samples/colors
@@ -15,8 +15,9 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 # Load gl-common.bash
-. ../gl-common.sh SAMPLE_SPINNER
-if [[ $? > 0 ]]; then echo "Error when loading file '../gl-common.sh'"; exit 1; fi
+readonly SAMPLES_DIR=$(dirname "$(echo "$(readlink -f "$0")" | sed -e 's,\\,/,g')")
+. "${SAMPLES_DIR}/../gl-common.sh" SAMPLES_
+if [[ $? > 0 ]]; then echo "Error when loading file '${SAMPLES_DIR}/../gl-common.sh'"; exit 1; fi
 
 test_color() {
     echo -e "$(eval "echo \${$1}")$1${NC}"
