Examples

diff --git a/examples/spinner b/examples/spinner
--- a/examples/spinner
+++ b/examples/spinner
@@ -15,9 +15,9 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 # Load gl-common.bash
-readonly SAMPLES_DIR=$(dirname "$(echo "$(readlink -f "$0")" | sed -e 's,\\,/,g')")
-. "${SAMPLES_DIR}/../gl-common.sh" SAMPLES_
-if [[ $? > 0 ]]; then echo "Error when loading file '${SAMPLES_DIR}/../gl-common.sh'"; exit 1; fi
+readonly EXAMPLE_DIR=$(dirname "$(echo "$(readlink -f "$0")" | sed -e 's,\\,/,g')")
+. "${EXAMPLE_DIR}/../gl-common.sh" EXAMPLE_
+if [[ $? > 0 ]]; then echo "Error when loading file '${EXAMPLE_DIR}/../gl-common.sh'"; exit 1; fi
 
 info "Press [Ctrl+C] to exit."
 
diff --git a/examples/text b/examples/text
--- a/examples/text
+++ b/examples/text
@@ -15,15 +15,18 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 # Load gl-common.bash
-readonly SAMPLES_DIR=$(dirname "$(echo "$(readlink -f "$0")" | sed -e 's,\\,/,g')")
-. "${SAMPLES_DIR}/../gl-common.sh" SAMPLES_
-if [[ $? > 0 ]]; then echo "Error when loading file '${SAMPLES_DIR}/../gl-common.sh'"; exit 1; fi
+readonly EXAMPLE_DIR=$(dirname "$(echo "$(readlink -f "$0")" | sed -e 's,\\,/,g')")
+. "${EXAMPLE_DIR}/../gl-common.sh" EXAMPLE_
+if [[ $? > 0 ]]; then echo "Error when loading file '${EXAMPLE_DIR}/../gl-common.sh'"; exit 1; fi
 
-# Declare help header
-SAMPLES_HELP_FILE="usage.md"
-SAMPLES_HELP_TITLE_PREFIX="test"
+has_option_wf "debug" "$@" # Used to trigger debug mode with flag --debug
 
-
-usage
-usage foo
-usage foo bar
+trace "a trace"
+info "an info"
+question "a question, "
+question "enter a text: " TEXT
+info "your text was: $TEXT"
+question "enter a text: " TEXT "there is a default value this time !"
+info "your text was: $TEXT"
+warn "a warn"
+debug "a debug"
